### ISSUE TITLE
macOS: ld: library not found for -lpri

### ISSUE THREAD

**Issue by superdump** [rennis250/processing-rs#1]
When trying to build a project against this crate on macOS, I get: `ld: library not found for -lpri`

What is the intended build process?

**Comment by sdroege** [comment]
It would probably make sense to have a `build.rs` around the [cc](https://crates.io/crates/cc) crate, that builds the `pri.c` and includes it in the crate

**Comment by superdump** [comment]
I'll make a PR. Just testing it...

**Comment by superdump** [comment]
See https://github.com/rennis250/processing-rs/pull/2

**Comment by rennis250** [comment]
Thanks, merged! That obviously slipped my attention. Sorry for any inconvenience.
