### ISSUE TITLE
Problem running the bench

### ISSUE THREAD

**Issue by barzilouik** [rennis250/processing-rs#3]
You're doing a wonderful project, a creative multimedia framework in rust is a must ;)
I hope you'll succeed (and I can use it in place of openframeworks/processing) .
This kind of framework is essential for teaching the language in itself.

I'm trying to run the included bench, and I'm having some troubles : 
platform : ubuntu mint 16.04
rust : nighly

$ cargo bench
   Compiling processing v0.2.0 (file:///*..*/Dev/Rust/processing-rs)
error[E0463]: can't find crate for `p5`
 --> benches/basic.rs:2:1
  |
2 | extern crate processingrs as p5;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

do you have a special setup for processingrs being a local crate ?

**Comment by rennis250** [comment]
Sorry about that! I had forgotten to update the name there. Also, this bench is actually an example, so I updated it appropriately. It is now updated for the latest version of the code. Check it out and let me know how it goes for you! :)
